os:
  - Visual Studio 2019

environment:
  matrix:
    - ACTION: vs2015
    - ACTION: vs2017

platform:
  - Win32
  - x64
    
configuration:
  - Release

install:
  - bin\premake5.exe %ACTION%
  
build:
  project: build\$(ACTION)\xatlas.sln
