name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup - cmake
      uses: lukka/get-cmake@latest
    - name: Configure
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: |
        cmake --build build --config Release

  Windows:
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup - cmake
      uses: lukka/get-cmake@latest
    - name: Configure
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: |
        cmake --build build --config Release
